### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Krzysiex008** [thesportstacker/discord.js-v12-bot-tutorial#14]
(node:3144) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
    at Object.run (C:\Users\Krzymsiu\Desktop\DiscordBot-1.26.1\src\commands\ping.command.js:15:25)
    at Client.<anonymous> (C:\Users\Krzymsiu\Desktop\DiscordBot-1.26.1\src\handlers\command.handler.js:150:11)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\Krzymsiu\Desktop\DiscordBot-1.26.1\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Krzymsiu\Desktop\DiscordBot-1.26.1\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Krzymsiu\Desktop\DiscordBot-1.26.1\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Krzymsiu\Desktop\DiscordBot-1.26.1\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Krzymsiu\Desktop\DiscordBot-1.26.1\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Krzymsiu\Desktop\DiscordBot-1.26.1\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kajg2008NL** [comment]
can you send the code?

**Comment by Krzysiex008** [comment]
> can you send the code?

nvm
